apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "coroot.com/v1",
          "kind": "Coroot",
          "metadata": {
            "name": "coroot",
            "namespace": "coroot"
          },
          "spec": {
            "clickhouse": {
              "replicas": 2,
              "shards": 3,
              "storage": {
                "size": "200Gi"
              }
            },
            "enterpriseEdition": {
              "licenseKey": LICENSE-KEY
            },
            "prometheus": {
              "storage": {
                "size": "100Gi"
              }
            }
          }
        }
      ]
    capabilities: Deep Insights
    features.operators.openshift.io/disconnected: 'true'
    features.operators.openshift.io/proxy-aware: 'false'
    features.operators.openshift.io/fips-compliant: 'false'
    features.operators.openshift.io/tls-profiles: 'false'
    features.operators.openshift.io/token-auth-aws: 'false'
    features.operators.openshift.io/token-auth-azure: 'false'
    features.operators.openshift.io/token-auth-gcp: 'false'
  name: coroot-operator.1.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Coroot is the Schema for the coroots API
        displayName: Coroot
        kind: Coroot
        name: coroots.coroot.com
        version: v1
  description: Coroot description
  displayName: Coroot
  install:
    strategy: deployment
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - endpoints
                - namespaces
                - nodes
                - persistentvolumes
                - pods
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
            - apiGroups:
                - ""
              resources:
                - persistentvolumeclaims
                - serviceaccounts
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
                - list
                - watch
            - apiGroups:
                - apps
              resources:
                - cronjobs
                - daemonsets
                - deployments
                - replicasets
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - batch
              resources:
                - cronjobs
                - jobs
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - coroot.com
              resources:
                - coroots
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - coroot.com
              resources:
                - coroots/finalizers
              verbs:
                - update
            - apiGroups:
                - coroot.com
              resources:
                - coroots/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterrolebindings
                - clusterroles
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - storage.k8s.io
              resources:
                - storageclasses
                - volumeattachments
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
          serviceAccountName: coroot-operator
      deployments:
        - label:
            app.kubernetes.io/name: coroot-operator
          name: coroot-operator
          spec:
            selector:
              matchLabels:
                app.kubernetes.io/name: coroot-operator
            strategy: {}
            template:
              metadata:
                labels:
                  app.kubernetes.io/name: coroot-operator
              spec:
                containers:
                  - image: ghcr.io/coroot/coroot-operator:1.0.2
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: operator
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 256Mi
                      requests:
                        cpu: 100m
                        memory: 64Mi
                securityContext:
                  runAsNonRoot: true
                serviceAccountName: coroot-operator
                terminationGracePeriodSeconds: 10
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - monitoring
  links:
    - name: Operator Source
      url: https://github.com/coroot/coroot-operator
  maturity: stable
  provider:
    name: Coroot Inc.
    url: https://coroot.com
  version: 1.0.2
  relatedImages:
    - name: coroot-operator
      image: ghcr.io/coroot/coroot-operator:1.0.2
    - name: coroot-ee
      image: ghcr.io/coroot/coroot-ee:1.5.15
    - name: coroot-node-agent
      image: ghcr.io/coroot/coroot-node-agent:1.22.0
    - name: coroot-cluster-agent
      image: ghcr.io/coroot/coroot-cluster-agent:1.1.1
    - name: clickhouse
      image: ghcr.io/coroot/clickhouse:24.8.4-ubi9-0
    - name: prometheus
      image: ghcr.io/coroot/prometheus:2.54.1-ubi9-0
    - name: kube-state-metrics
      image: ghcr.io/coroot/kube-state-metrics:2.13.0-ubi9-0
